spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/payment;MODE=MYSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        auto_quote_keyword: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace


##########################################
portone:
    api:
      uri: https://a4d45e1a-22c9-497a-8692-93c3185e07ed.mock.pstmn.io