spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/payment;MODE=MYSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        auto_quote_keyword: trues
    # 애플리케이션 실행 시 기초 데이터 삽입s
    defer-datasource-initialization: true
  # 모든 데이터베이스에 sql 스크립트를 동작
  sql:
    init:
      mode: always


logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace


##########################################
portone:
    api:
      uri: https://a4d45e1a-22c9-497a-8692-93c3185e07ed.mock.pstmn.io